# a,  b  = print(sum((map(int, input().split())))) 
# # print(a + b)
# # print(a - b)
# # print(a * b)
# # print(a / b)
# # print(a % b)

# a, b = map(int, input().split())
# print(a + b)
# print(a - b)
# print(a * b)
# print(a / b)
# print(a % b)

a, b = map(int, input().split())
print(a + b)
print(a - b)
print(a * b)
print(a // b)
print(a % b)